---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
  
    - name: Pull Image
      shell: docker pull siddharthkothari9403/calculator:latest

    - name: Run the container
      shell: docker create -it --name Calculator siddharthkothari9403/calculator