---
- name: Pull Docker Image of Calculator
  hosts: all

  tasks:
  
    - name: Pull Image
      shell: docker pull siddharthkothari9403/calculator:latest

    - name: Remove running container with older version
      shell: docker rm -f calculator

    - name: Run the container
      shell: docker run -it -d --name calculator siddharthkothari9403/calculator